version: 2
jobs:
  server_deploy:
    #TODO

  app_s3_sync:

    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo/app

    steps:
      - setup_remote_docker:
          docker_layer_caching: false

      - checkout:
          path: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: |
            source ~/.bashrc;
            yarn test;

      - run:
          name: Sync Build Files to S3 Bucket
          command: |
            source ~/.bashrc;
            sudo apt-get update && sudo apt-get install -y python-dev;
            sudo curl -O https://bootstrap.pypa.io/get-pip.py;
            sudo python get-pip.py;
            sudo pip install awscli --upgrade;
            yarn build;
            aws s3 sync build/ s3://www.chautari.cf --delete;

workflows:
  version: 2
  deploy_server:
    jobs:
      - server_deploy:
          filters:
            branches:
              only:
                - dev
                - master
  deploy_app:
    jobs:
      - app_s3_sync:
          filters:
            branches:
              only:
                - dev
                - master
